### ISSUE TITLE
Scrollbar / Legend not working

### ISSUE THREAD

**Issue by macandcheese** [ThumbsAlmighty/amCharts-Angular#10]
Thanks for this, got the chart set up fine.. Having a problem displaying scrollbar / legends. Even if you enable them in the controller 
"
    legend: [ {
      enabled: true
    } ]
    chartScrollbar: [ {
      enabled: true
      graph: 'value'
      graphType: 'smoothedLine'
      autoGridCount: true
      scrollbarHeight: 40
    } ]
"

They won't render... I'm using the CDN version of the directive.js for dev, but would that be the right place to declare these, assuming hosted directive.js in a prod environment?

**Comment by GrantMStevens** [comment]
This is an issue I am aware of, but haven't bothered to address yet. I'll try to take a look at resolving it when I find some time.

**Comment by macandcheese** [comment]
Awesome, thanks for the quick response. I'll see if I can get something working in the meantime.

**Comment by GrantMStevens** [comment]
Alrighty, I made some time over lunch and added some new code in to support a legend and chartScrollbar. I updated the jsfiddle in the readme (http://jsfiddle.net/w3vpc35o/10/) so you can see it in action. For the chartScrollbar, make sure you include the path to the AmCharts images folder (or CDN like my fiddle uses), or you'll just get broken images for the scroll indicators. The AmCharts docs should be able to get you the rest of the way. I'll be traveling for work for the next month, so I'll look in to extending this even more if I have some down time.

**Comment by macandcheese** [comment]
Nice work. Doesn't seem to be extending through variables in the controller (height, position, colors, etc., don't seem to work). Appreciate the work on this.
