### ISSUE TITLE
charts are not responsive

### ISSUE THREAD

**Issue by nickeliah1** [ThumbsAlmighty/amCharts-Angular#11]
I have set the chart option
responsive: {
     enabled: true
},

and included the plugin, as required here:
http://www.amcharts.com/tutorials/making-charts-responsive/

looks like the directive is setting the width and height to a fixed number.. maybe it needs an option for responsive?

**Comment by nickeliah1** [comment]
oops.. set width to 100% and fixed

**Comment by GrantMStevens** [comment]
Yeah, I'm thinking about removing that default, as it doesnt seem to be doing much good any more.

**Comment by nickeliah1** [comment]
Yeah the fixed size is probably not necessary :)
