### ISSUE TITLE
Can you include a sample app?

### ISSUE THREAD

**Issue by calloncampbell** [ThumbsAlmighty/amCharts-Angular#12]
I'm new to Angular so it would be nice if there was a working sample app instead of trying to piece things together from docs and JSFIDDLE.

**Comment by GrantMStevens** [comment]
The JSFiddle demo is technically a full Angular application. Just copy the html from the fiddle in to the body of your HTML, add your script reference to Angular, then create a js file containing the js from the fiddle and reference it in your project.

If you're having trouble understanding how to use this directive, perhaps you would be better served visiting some more comprehensive Angular tutorials to learn the ins and outs of the framework. I'm not going to devote time to building and hosting a sample app somewhere. Sorry.

**Comment by calloncampbell** [comment]
Thanks, that helps. I know how to use the directive, I’m actually trying to create a new one for the AmMap. AmCharts support personal directed me to your github repos to get an idea.

Sent from Windows Mail

From: Grant
Sent: ‎Thursday‎, ‎June‎ ‎25‎, ‎2015 ‎1‎:‎22‎ ‎PM
To: GrantMStevens/amCharts-Angular
Cc: Callon Campbell

The JSFiddle demo is technically a full Angular application. Just copy the html from the fiddle in to the body of your HTML, add your script reference to Angular, then create a js file containing the js from the fiddle and reference it in your project.

If you're having trouble understanding how to use this directive, perhaps you would be better served visiting some more comprehensive Angular tutorials to learn the ins and outs of the framework. I'm not going to devote time to building and hosting a sample app somewhere. Sorry.

**Comment by GrantMStevens** [comment]
Ahh, I see. Well, hopefully my code helps. Good luck.

**Comment by calloncampbell** [comment]
Hi Grant,

Just wanted to let you know that your work on the amChart directive really helped me with creating an amMap directive. 

Thanks

Callon

Sent from Windows Mail

From: Grant
Sent: ‎Thursday‎, ‎June‎ ‎25‎, ‎2015 ‎7‎:‎56‎ ‎PM
To: GrantMStevens/amCharts-Angular
Cc: Callon Campbell

Ahh, I see. Well, hopefully my code helps.

**Comment by GrantMStevens** [comment]
Glad it helped!
