### ISSUE TITLE
the directive is not work with pie chart

### ISSUE THREAD

**Issue by golfapipol** [ThumbsAlmighty/amCharts-Angular#15]
I have data like this in option
{                "type": "serial",
                "categoryField": "category",
                "startDuration": 0,
                "columnSpacing": 0,
                "columnWidth": 0.5,
                "categoryAxis": {
                    "gridPosition": "start",
                    "gridColor": border,
                    "gridAlpha": 1,
                    "labelOffset": 5,
                    "fontSize": 11,
                    "axisColor": border
                },
                "valueAxes": [
                    {
                        "id": "ValueAxis-1",
                        "gridColor": border,
                        "gridAlpha": 1,
                        "fontSize": 11,
                        "axisColor": border,
                    }
                ],
                "balloon": { 
                    "color": "#444444",
                    "borderThickness": 0, 
                    "cornerRadius": 3, 
                    "shadowAlpha": 0,
                    "fillColor" : "#F1F1F1",
                    "fillAlpha" : 1
                },
                "trendLines": [],
                "graphs": [
                    {
                        "fillAlphas": 1,
                        "lineThickness": 0,
                        "id": "AmGraph-1",
                        "title": "Positive",
                        "type": "column",
                        "valueField": "column-1",
                        "fillColors": green
                    },
                    {
                        "fillAlphas": 1,
                        "lineThickness": 0,
                        "id": "AmGraph-2",
                        "title": "Neutral",
                        "type": "column",
                        "valueField": "column-2",
                        "fillColors": yellow
                    }
                ],
                "guides": [],
                "allLabels": [],
                "dataProvider": [
                    {
                        "category": "16:25",
                        "column-1": 16,
                        "column-2": 44
                    },
                    {
                        "category": "16:30",
                        "column-1": 32,
                        "column-2": 38
                    },
                    {
                        "category": "16:35",
                        "column-1": 24,
                        "column-2": 56
                    },
                    {
                        "category": "16:40",
                        "column-1": 28,
                        "column-2": 40
                    },
                    {
                        "category": "16:45",
                        "column-1": 65,
                        "column-2": 20
                    },
                    {
                        "category": "16:50",
                        "column-1": 13,
                        "column-2": 30
                    },
                    {
                        "category": "16:55",
                        "column-1": 24,
                        "column-2": 24
                    },
                    {
                        "category": "17:00",
                        "column-1": 16,
                        "column-2": 34
                    }
                ]

**Comment by GrantMStevens** [comment]
If you are trying to create a pie chart, the type needs to be "pie" not "serial". Look at some of the pie chart examples on the AmCharts website to get a better idea as to the conventions used to create them.

**Comment by GrantMStevens** [comment]
Also, in looking at my code, I havent built this for pie charting. I'll have to update it.

**Comment by GrantMStevens** [comment]
Ok, I have updated the directive for support with pie charts. Here is a very simple jsfiddle that illustrates this functionality. Make sure you reference pie.js from the AmCharts libs in order to use it.

http://jsfiddle.net/w3vpc35o/34/

**Comment by golfapipol** [comment]
thank you and sorry for wrong data and i use directive with another graph 
it not work 
what I did wrong 
sorry for bad grammar
I get sample data from demo jQuery Version
$scope.multi_graph = {
            "type": "serial",
                "path": "http://www.amcharts.com/lib/3/",
                "color": font_color_low,
                "balloonText": "[[percents]]%",
                "categoryField": "category",
                "categoryAxis": {
                    "gridPosition": "start",
                    "gridColor": "#EFEFEF",
                    "gridAlpha": 1,
                    "labelOffset": 10,
                    "fontSize": 11,
                    "axisColor": "#EFEFEF"
                },
                "valueAxes": [
                    {
                        "id": "ValueAxis-1",
                        "gridColor": "#EFEFEF",
                        "gridAlpha": 1,
                        "fontSize": 11,
                        "axisColor": "#EFEFEF",
                    }
                ],
                "balloon": { 
                    "color": "#444444",
                    "borderThickness": 0, 
                    "cornerRadius": 3, 
                    "shadowAlpha": 0,
                    "fillColor" : "#F1F1F1",
                    "fillAlpha" : 1
                },
                "graphs": [
                    {
                        "bullet": "round","bulletSize": 7,"id": "AmGraph-1",
                        "lineThickness": 2,"valueField": "column-1",
                        "lineColor": "#fdcb35","type": "smoothedLine"
                    },
                    {
                        "bullet": "round","bulletSize": 7,
                        "id": "AmGraph-2","lineThickness": 2,
                        "valueField": "column-2", "lineColor": "#4ECDC4","type": "smoothedLine"
                    },
                    {
                        "bullet": "round","bulletSize": 7,"id": "AmGraph-3",
                        "lineThickness": 2,"valueField": "column-3","lineColor": "#2C5995",
                        "type": "smoothedLine"
                    }
                ],
                "guides": [],"allLabels": [],"trendLines": [],
                "data": [
                    {"category": "16:25","column-1": 0,"column-2": 0,"column-3": 0},
                    {"category": "16:30","column-1": 45,"column-2": 15,"column-3": 25},
                    {"category": "16:35","column-1": 90,"column-2": 0,"column-3": 30},
                    {"category": "16:40","column-1": 20,"column-2": 275,"column-3": 475},
                    {"category": "16:45","column-1": 290,"column-2": 80,"column-3": 15},
                    {"category": "16:50","column-1": 10,"column-2": 170,"column-3": 30},
                    {"category": "16:55","column-1": 45,"column-2": 75,"column-3": 75},
                    {"category": "17:00","column-1": 0,"column-2": 0,"column-3": 0}
                ]
    };
<img width="898" alt="screen shot 2558-08-03 at 20 28 40" src="https://cloud.githubusercontent.com/assets/8346755/9038544/3b2ddd38-3a1f-11e5-9dd1-edd840197791.png">
<img width="642" alt="screen shot 2558-08-03 at 20 33 15" src="https://cloud.githubusercontent.com/assets/8346755/9038545/3b55486e-3a1f-11e5-881c-3ba7254b4d41.png">

**Comment by GrantMStevens** [comment]
Yeah, if you want any sample data, go to http://www.amcharts.com/demos/ and scroll down to the pie charts section. If you go in to each one, it'll have a demo of the chart and an edit button in the top right. Clicking the edit button will allow you to see the code behind the demo.

The serial charts and pie charts have very different properties, so you can't use the examples interchangeably.
