### ISSUE TITLE
Jsfiddle not working

### ISSUE THREAD

**Issue by mavencode01** [ThumbsAlmighty/amCharts-Angular#16]
I'm trying to use your directive here but not working...still looking to see if I can fix this.

The jsfiddle code looks like it's broken

**Comment by GrantMStevens** [comment]
I fixed this issue. When I changed the height and width defaults to 100%, I forgot to go update the JSFiddle to set a height and width on the parent element of the directive. Percentage heights require the parent to have a valid height property set (percentage of their parent or a pixel value).
