### ISSUE TITLE
Chart margins clipping scrollbar handles

### ISSUE THREAD

**Issue by pcasa** [ThumbsAlmighty/amCharts-Angular#17]
Recently chart.margin\* was set to 0 causing default scrollbar handles to be clipped on the edges.
https://github.com/GrantMStevens/amCharts-Angular/blob/e1194dcb3d54a253b15288912852fc65715fdf4c/dist/amChartsDirective.js#L55-L58

Commenting these lines out fixes this.

Did a quick jsFiddle to compare http://jsfiddle.net/hd5rhuoz/1/

**Comment by GrantMStevens** [comment]
Hmm, this wasn't an issue before, but I can see what you mean. It only appears to be an issue on charts with a scroll bar, as it looks like the superfluous white space isnt as apparent when the scroll bar is there. 

My suggestion for now would be to set the marginRight property yourself to add in the necessary white space so the scroll bar doesn't get pushed out of the viewable area. I can look in to removing those defaults in a future release.

**Comment by pcasa** [comment]
Is there a way to do that?  Based on code attached above looks like there is no way to override this.

**Comment by GrantMStevens** [comment]
Sure there is.

http://jsfiddle.net/hd5rhuoz/2/

see line 63.

**Comment by pcasa** [comment]
Perfect.  Knowing this, then there really is not an issue.

**Comment by GrantMStevens** [comment]
Ok great. I'll update the readme or comment the code to go in to more detail about overriding properties, as I do have multiple people with related questions.
