### ISSUE TITLE
Automatically generate element id if id has not been explicitly provided

### ISSUE THREAD

**Issue by DaniilHarik** [ThumbsAlmighty/amCharts-Angular#18]
Hello,

I'm displaying my amCharts inside ng-repeat and there is an issue with assigning element id to multiple charts within the loop.  

The  $index is not getting parsed by AngularJS at this point. Maybe it would make sense to add a check at the line 17 and assign random id if the id has not been explicitly provided?

Thanks a lot for a great directive :)

**Comment by GrantMStevens** [comment]
Why would the $index not be available to assign the id attribute on an element? I suppose I can add a random ID in the event one isnt provided, but this should be possible in the view.
