### ISSUE TITLE
Cannot create a Funnel chart

### ISSUE THREAD

**Issue by gitstc** [ThumbsAlmighty/amCharts-Angular#20]
Hi,

How can I use this directive to create a funnel chart? I took a look at the amChartsDirective.js file and noticed that it supports the XY,Pie and Serial charts. It does not seem to support the Funnel chart.

I tried the following code but it did not work:
$scope.amOptions = {
                type: "funnel",
                neckHeight: "30%",
                neckWidth: "40%",
                titleField: "title",
                valueField: "value",
                data: [
                    {
                        title: "Website visits",
                        value: 300
                    },
                    {
                        title: "Downloads",
                        value: 123
                    }
                ]
            };

Is the Funnel chart supported?

**Comment by GrantMStevens** [comment]
The funnel chart will not work with this directive right now. It could be a relatively trivial change, but I haven't had any time as of late to look at this.

**Comment by gitstc** [comment]
Thank you for your reply. I am going to try using the jQuery library
instead until this feature gets implemented.

**Comment by GrantMStevens** [comment]
Added support for funnel charts in 83933878b18ae5f080b0a6ebffb057c0af10d7f3
