### ISSUE TITLE
Cannot install specific version by bower

### ISSUE THREAD

**Issue by tetor** [ThumbsAlmighty/amCharts-Angular#25]
Hello :smiley: 

Bower uses git tag to resolve version number, not `bower.json` version property.

http://bower.io/docs/creating-packages/#version

> version
> 
> String
> 
> Deprecated. Use git or svn tags instead. This field is ignored by Bower.

And, its format must be semver. (maybe… I don't have confidence :sweat: )

http://bower.io/docs/pluggable-resolvers/#creating

> Resolvers should also follow semver specification.

Why don't you make tag again :question:

**Comment by GrantMStevens** [comment]
I had never really used tags before, so I got them all messed up. As of the latest release (83933878b18ae5f080b0a6ebffb057c0af10d7f3), tags should work and allow you to target releases.
