### ISSUE TITLE
Redraw on options change

### ISSUE THREAD

**Issue by asllad** [ThumbsAlmighty/amCharts-Angular#27]
It would be nice if there is an redraw for the chart if the options are changed.
I added it on the top of the link function.

``` javascript
    link: function ($scope, $el) {
      $scope.$watch('options', function(newOptions, oldOptions) {
        if (!angular.equals(newOptions, oldOptions)) {
          renderChart(newOptions);
        }
      }, true);
```

**Comment by GrantMStevens** [comment]
What else do you need to redraw other than data? Adding a watcher to the entire options property could cause unexpected redraws for some people and it is not good practice in my opinion. There are already events in place in this directive to manually handle chart rerenders.

**Comment by asllad** [comment]
I use this to activate translations for axis and graphs or update the chart with new metadata rules.
If you had a better idea how i could solve this, i would be happy.

**Comment by kirantambe** [comment]
To redraw i had to broadcast the 'amCharts.updateData' event.  is this right?

**Comment by GrantMStevens** [comment]
Yes, you can use 'amCharts.updateData' to redraw when you have new data. If you need to update other properties on the chart, you can use 'amCharts.renderChart' to completely rerender the chart.

**Comment by GrantMStevens** [comment]
@asllad You should use the 'amCharts.renderChart' event that I am listening for to rerender your chart as necessary. That prevents me from having to add a watcher to the entire options property, which still giving you the freedom to render the chart of data changes (just add your own watcher in the parent controller on the object you pass in to the directive, then handle its change and broadcast the event).
