### ISSUE TITLE
Not workign with AmCharts 3.17.x

### ISSUE THREAD

**Issue by swayams** [ThumbsAlmighty/amCharts-Angular#29]
Hi,

I am unable to get this working with amCharts 3.17.x. Is this compatible with 3.17.x. Please refer -
https://jsfiddle.net/c3uf0qjs/

Thanks

**Comment by GrantMStevens** [comment]
Your fiddle references version 3.13. Also, cdnjs doesnt even have 3.17 available, so if you're just trying to version up the script tags, of course you'll get failures. This is why looking at the console to see the error before posting these issues is great and prevents me from having to sort through these non-issues. I looked through the release notes from the version I am using in the examples all the way through the latest release, and I see nothing that would cause any issues. If you can provide me with a fiddle that indicates there is an issue, then I'll look in to it.
