### ISSUE TITLE
Question on stacked chart

### ISSUE THREAD

**Issue by balbler** [ThumbsAlmighty/amCharts-Angular#3]
Hi,
i am somewhat lost on creating a stacked chart with the directive.
What would be the suggested dataformat for the data object for a stacked chart?

cheers
bernhard

**Comment by GrantMStevens** [comment]
For any type of stacked chart, you will need to add multiple graphs.

The 'graphs' property on the object you pass as options in to the directive is an array. Each graph in that array would represent one 'section' in the 'stack'. All you'll need to do is to make sure your data is formatted appropriately, then add the appropriate number of graphs. Look at the stacked column chart example on the AmCharts website: http://www.amcharts.com/demos/stacked-column-chart/#theme-light.

In that example, you can see how the data is being formatted, and you can also see that the chart is getting instantiated with multiple graphs to create the desired stacked view. This directive uses the same general object structure, which should make translating those examples very easy.
