### ISSUE TITLE
How to render real time data for update dynamically.

### ISSUE THREAD

**Issue by bahadur** [ThumbsAlmighty/amCharts-Angular#52]
I want to add additional data to chart that already rendered. Like the data i received from the source updated every 10 second.
Could you please help me in this?

Thanks

**Comment by PemmasaniRajesh** [comment]
I need this very badly, could you #GrantMStevens please comment on this?

**Comment by bahadur** [comment]
I got this. #GrantMStevens already provides event for updating data "amCharts.updateData". We just need to broadcast that event. 
$scope.$broadcast('amCharts.updateData', options, 'id');

Hope this will help.

**Comment by PemmasaniRajesh** [comment]
I understand that options is nothing but data we're going to update and what is that id?

**Comment by bahadur** [comment]
`<am-chart` id="myFirstChart" options="amChartOptions" height="350px" width="100%"></am-chart>

$scope.$broadcast('amCharts.updateData', options, 'myFirstChart');

**Comment by GrantMStevens** [comment]
@bahadur is correct. You should be using the `updateData` event to update the chart data.
