### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by PemmasaniRajesh** [ThumbsAlmighty/amCharts-Angular#55]
responsive is not working, could you please tell me how to make it ?

I've already used    <script src="Scripts/amcharts/responsive/responsive.min.js"></script> and code as

 responsive: {
            enabled: true
        },

but it is not working.

**Comment by GrantMStevens** [comment]
Are you including the responsive script?

This CodePen from the AmCharts team provides an example: http://codepen.io/amcharts/pen/QwgEKQ/
