### ISSUE TITLE
amChartOptions.defs not passed

### ISSUE THREAD

**Issue by nielsch** [ThumbsAlmighty/amCharts-Angular#57]
The '.defs' attribute of the amChartOptions is not passed to the chart. Therefore it is not possible to add filters like shadows to the charts. 
Example of how this is used without the angular wrapper:
https://www.amcharts.com/tutorials/svg-filters/

This can be fixed by passing the .defs attribute on to the chart like this:

```
if(o.defs) {
    chart.defs = o.defs;
}
```

**Comment by GrantMStevens** [comment]
send me a pull request and I'll get it merged. I havent had any time to work on this lately.
