### ISSUE TITLE
TypeError: undefined is not a function     at renderChart (http://localhost:3000/bower_components/amcharts-angular/dist/amChartsDirective.js:39:21)

### ISSUE THREAD

**Issue by brucejcw** [ThumbsAlmighty/amCharts-Angular#6]
> TypeError: undefined is not a function
>     at renderChart (http://localhost:3000/bower_components/amcharts-angular/dist/amChartsDirective.js:39:21)

anyone know why it happens ? I just copy the example in README

Thanks for any help

**Comment by brucejcw** [comment]
I found the reason, it is because the serial.js is not automatically added in angular-gulp

**Comment by brucejcw** [comment]
@ThumbsAlmighty yeah, I finally found this issue, It is better if you add it in bower.json :) Thanks

**Comment by GrantMStevens** [comment]
I'll look in to adding the dependency.
