### ISSUE TITLE
Using directive in tabs

### ISSUE THREAD

**Issue by MotherCake** [ThumbsAlmighty/amCharts-Angular#64]
Hi

I want to use the directive in tabs. Therefore in need to call chart.invalidateSize();
How can I access the chart object?

**Comment by developer1** [comment]
You'll need to bind to the "chart" binding, you'll then be able to manipulate the raw chart object.

`<am-chart options="amChartOptions" chart="myChart"></am-chart>`

`myChart.invalidateSize();`

**Comment by MotherCake** [comment]
thx for your help. that's what I searched for.
