### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by yeeland** [ThumbsAlmighty/amCharts-Angular#71]
Is there any chance you can publish this to npm? Thanks!

**Comment by GrantMStevens** [comment]
Its already on NPM, hence the package.json file in the root of the project

**Comment by yeeland** [comment]
https://www.npmjs.com/search?q=amcharts-angular

**Comment by deftomat** [comment]
Unfortunately, I cannot find it on NPM now.

**Comment by WuglyakBolgoink** [comment]
Sorry, no results for ‘amcharts-angular’

> Its already on NPM, hence the package.json file in the root of the project

you need publish!!! alone "package.json" doesn't matter with npm-repo 😄
