### ISSUE TITLE
categoryAxis may not be working properly

### ISSUE THREAD

**Issue by BaranOrnarli** [ThumbsAlmighty/amCharts-Angular#77]
Adding this to your serial chart could cause the graph not to show up (but it works using the regular amchart library).

Just remove it and amchart directive works.

```
"categoryAxis": {
                    "gridPosition": "start",
                    "fillAlpha": 0.05,
                    "axisColor": "#333",
                    "position": "left"
                },
```

**Comment by DimitriMathot** [comment]
Hello is there a way to make it work with the directive or does anyone get a solution to rotate the label of the categoryAxis?

**Comment by GrantMStevens** [comment]
I cannot replicate this. Adding these works just fine.

http://jsfiddle.net/w3vpc35o/440/
