### ISSUE TITLE
amChart is not working in BootStrap Tab (Resize Issue)

### ISSUE THREAD

**Issue by shreeshagundmi** [ThumbsAlmighty/amCharts-Angular#78]
Hi There,

I am using amChart inside Bootstrap Tab.
When i open the tab i wont get any data inside the tab but when i resize the window the chart is comming.
please look into the attached screenshot

Please help me as soon as possible

I tried bellow both solution's
```
<am-chart id="insightFirstChart" options="amChartOptions" chart="InsightChart"></am-chart>

Onclick() event i'm doing bellow operations. 
<script>
    function myFunction() {
        InsightChart.invalidateSize();
    }
</script>

I am getting this error
Uncaught ReferenceError: InsightChart is not defined
```

Before Resizing the window
![amchart res](https://cloud.githubusercontent.com/assets/24886410/24143380/7e8268f0-0e4f-11e7-81ad-71e32e4597c1.jpg)

After Resizing
![amchart res2](https://cloud.githubusercontent.com/assets/24886410/24143393/8a0dfd4c-0e4f-11e7-8c7d-b89d98de47fd.jpg)

**Comment by GrantMStevens** [comment]
You are trying to reference your chart from the `window` object, not from the `$scope` object that it gets assigned to.
