### ISSUE TITLE
starting point example

### ISSUE THREAD

**Issue by mg1075** [ThumbsAlmighty/amCharts-Angular#9]
There would be multiple benefits if there could be a pointer to a plunkr, jsbin, etc. to a working example of the directive.

**Comment by mg1075** [comment]
I have added a starting point example on plunkr using Angular 1.4.

http://plnkr.co/edit/DYzEH8KGVwBu5OYbAgEV?p=preview

There was a problem with the directive, in that the height and width passed were not being processed until I put the 'px` in the height and width declaration in the directive. 

Actually, I think this an incorrect default for the directive. The default should not be a fixed chart; the default should be a **responsive** chart, which amCharts has a provision for.

**Comment by GrantMStevens** [comment]
I have modified the readme to include a jsfiddle example that better illustrates how to use this directive.
